from django.urls import path     

from . import views
urlpatterns = [
    path('state_view', views.state_view),
    path('state_form', views.state_form),
    path('state_record', views.state_record),
    path('state_update', views.state_update),
    path('<int:number>/state_edit/', views.state_edit),
    path('model_view', views.model_view),
    path('model_form', views.model_form),
    path('model_record', views.model_record),
    path('model_update', views.model_update),
    path('<int:number>/model_delete/', views.model_delete),
    path('<int:number>/model_edit/', views.model_edit),
    path('brand_view', views.brand_view),
    path('brand_form', views.brand_form),
    path('brand_record', views.brand_record),
    path('brand_update', views.brand_update),
    path('<int:number>/brand_delete/', views.brand_delete),
    path('<int:number>/brand_edit/', views.brand_edit),
    path('item_view', views.item_view),
    path('item_form', views.item_form),
    path('item_record', views.item_record),
    path('item_update', views.item_update),
    path('<int:number>/item_delete/', views.item_delete),
    path('<int:number>/item_edit/', views.item_edit),
    path('employee_view', views.employee_view),
    path('employee_form', views.employee_form),
    path('employee_record', views.employee_record),
    path('employee_update', views.employee_update),
    path('<int:number>/employee_delete/', views.employee_delete),
    path('<int:number>/employee_edit/', views.employee_edit),
    path('address_view', views.address_view),
    path('address_form', views.address_form),
    path('address_record', views.address_record),
    path('address_update', views.address_update),
    path('<int:number>/address_delete/', views.address_delete),
    path('<int:number>/address_edit/', views.address_edit),
    path('vehicle_view', views.vehicle_view),
    path('vehicle_form', views.vehicle_form),
    path('vehicle_record', views.vehicle_record),
    path('vehicle_update', views.vehicle_update),
    path('<int:number>/vehicle_delete/', views.vehicle_delete),
    path('<int:number>/vehicle_edit/', views.vehicle_edit)
]
