from django.urls import path     

from . import views
urlpatterns = [
    path('', views.index),
    path('login', views.login_query),
    path('login_form', views.login_form),
    path('register_form', views.register_form),
    path('register_record', views.register_record),
    path('dashboard', views.dashboard),
    path('close', views.close),
    path('view', views.view),
    path('update', views.update),
    path('<int:number>/delete/', views.delete),
    path('<int:number>/edit/', views.edit)
    
    # path('dashboard', views.dashboard),
    # path('register_form', views.register_form),
    # path('register_record', views.register_record),
    # path('login_form', views.login_form),
    # path('customer_view', views.customer_view),
    # path('customer_form', views.customer_form),
    # path('customer_record', views.customer_record),
    # path('customer_update', views.customer_update),
    # path('<int:number>/customer_delete/', views.customer_delete),
    # path('<int:number>/customer_edit/', views.customer_edit),
    # path('item_view', views.item_view),
    # path('item_form', views.item_form),
    # path('item_record', views.item_record),
    # path('item_update', views.item_update),
    # path('<int:number>/item_delete/', views.item_delete),
    # path('<int:number>/item_edit/', views.item_edit),
    # path('action_view', views.action_view),
    # path('action_form', views.action_form),
    # path('action_record', views.action_record),
    # path('action_update', views.action_update),
    # path('<int:number>/action_delete/', views.action_delete),
    # path('<int:number>/action_edit/', views.action_edit),
    # path('project_view', views.project_view),
    # path('project_form', views.project_form),
    # path('project_record', views.project_record),
    # path('project_update', views.project_update),
    # path('<int:number>/project_delete/', views.project_delete),
    # path('<int:number>/project_edit/', views.project_edit),
    # path('activity_view', views.activity_view),
    # path('activity_form', views.activity_form),
    # path('activity_record', views.activity_record),
    # path('activity_update', views.activity_update),
    # path('<int:number>/activity_delete/', views.activity_delete),
    # path('<int:number>/activity_edit/', views.activity_edit)
]
